#specify the version
version: "3.8"

#generate the services needed
services:

 redis:
    container_name: "redis"
    image: "redis:alpine"
    
    #add the custom conf file to use and a custom pw
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass P@ssw0rd890

    ports:
     - "6379:6379"
    
    #map the volumes to use the custom conf file from this project
    volumes:
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

